duet:
    dropout: 0.5
    max_query_terms: 20
    max_doc_terms: 200
    num_hidden_nodes: 512
    term_window_size: 3
    pooling_kernel_width_query: 18 #20 -3 +1 = 18
    pooling_kerner_with_doc: 100
    num_pooling_windows_doc: 99 #(MAX_DOC_TERMS - TERM_WINDOW_SIZE + 1) - POOLING_KERNEL_WIDTH_DOC + 1 (200 - 3 + 1) - 100 + 1 = 99
    num_ngraphs: 0
    learning_rate: 0.001
training:
    device: 'torch.device(\"cuda:0\")'
    mb_size: 1024
    num_epochs: 1
    epoch_size: 1024
    data_dir: '/home/erasmus/Documents/Official Data/Ranking'
    data_file_ngraphs: '/home/erasmus/Documents/Official Data/Ranking/ngraphs.txt'
    data_file_idfs: '/home/erasmus/Documents/Official Data/Ranking/idf.norm.tsv'
    data_file_train : '/home/erasmus/Documents/Official Data/Ranking/triples.train.small.tsv'
predict:
    data_file_dev: '/home/erasmus/Documents/Official Data/Ranking/top1000.dev.tsv"'
eval:
    qrels_dev: '/home/erasmus/Documents/Official Data/Ranking/qrels.dev.tsv'

